# Generated by Django 3.2.9 on 2022-01-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='user_sts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
