# Generated by Django 4.0.2 on 2022-08-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_auto_20220105_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesAdditionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdded', models.BooleanField(default=False)),
            ],
        ),
    ]
