# Generated by Django 4.0.2 on 2022-08-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_candidatesadditionstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatesAdditionStatus',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='user_sts',
            new_name='isCandidateAdded',
        ),
    ]
