# Generated by Django 4.0.2 on 2022-08-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_delete_candidatesadditionstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='isCandidateAdded',
        ),
    ]
