# Generated by Django 4.0.2 on 2022-08-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_candidatesadditionstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatesAdditionStatus',
        ),
    ]
