# Generated by Django 3.2.9 on 2021-12-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211206_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
