# Generated by Django 3.2.9 on 2021-12-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20211206_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
