# Generated by Django 3.2.9 on 2021-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211206_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
