# Generated by Django 3.2.9 on 2021-12-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211213_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
