# Generated by Django 3.2.9 on 2021-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.IntegerField(choices=[(1, 'Weak'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], default=1),
        ),
    ]
