# Generated by Django 3.2.9 on 2021-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizenship_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='grand_father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='provience_number',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
