# Generated by Django 3.2.9 on 2021-12-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211213_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='citizenship_number',
        ),
    ]
