# Generated by Django 3.2.9 on 2021-12-14 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_image_profile_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob_ad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dob_bs',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='docs_back',
            field=models.ImageField(default='default.jpg', upload_to='docs_back'),
        ),
        migrations.AddField(
            model_name='profile',
            name='docs_front',
            field=models.ImageField(default='default.jpg', upload_to='docs_front'),
        ),
    ]
